database:
  host: "host.docker.internal"
  user: "postgres"
  password: "root"
  name: "go-grpc-auth"
  port: 5435
  sslmode: "disable"

server:
  port: ":50051"

jwt:
  secret: "your_super_secret_key"
