database:
  host: "localhost"
  user: "postgres"
  password: "root"
  name: "go-grpc-auth"
  port: 5432
  sslmode: "disable"
  timezone: "Asia/Dhaka"

server:
  port: ":50051"

jwt:
  secret: "your_super_secret_key"
