database:
  # host: "host.docker.internal"
  host: "localhost"
  user: "postgres"
  password: "root"
  name: "go-grpc-auth"
  port: 5432
  sslmode: "disable"

server:
  grpc_port: ":50051"
  http_port: ":8080"

jwt:
  secret: "your_super_secret_key"
